#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\_Ace_Layout.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_Ace_Layout.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 2 "..\..\Views\Shared\_Ace_Layout.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Ace_Layout.cshtml")]
    public partial class _Views_Shared__Ace_Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Ace_Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\_Ace_Layout.cshtml"
  
    var menu = ManageProvider.Menu.Current;
    var set = NewLife.Cube.Setting.Current;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"zh-CN\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"新生命团队,NewLife,魔方,Cube,XCode\"");

WriteLiteral(" />\r\n    ");

WriteLiteral("\r\n    <title>");

            
            #line 16 "..\..\Views\Shared\_Ace_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 16 "..\..\Views\Shared\_Ace_Layout.cshtml"
                       Write(SysConfig.Current.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 570), Tuple.Create("\"", 590)
, Tuple.Create(Tuple.Create("", 577), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 577), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 645), Tuple.Create("\"", 684)
, Tuple.Create(Tuple.Create("", 652), Tuple.Create<System.Object, System.Int32>(Href("~/Template/css/bootstrap.min.css")
, 652), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 716), Tuple.Create("\"", 771)
, Tuple.Create(Tuple.Create("", 723), Tuple.Create<System.Object, System.Int32>(Href("~/Template/font-awesome/css/font-awesome.min.css")
, 723), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 803), Tuple.Create("\"", 836)
, Tuple.Create(Tuple.Create("", 810), Tuple.Create<System.Object, System.Int32>(Href("~/Template/css/animate.css")
, 810), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 868), Tuple.Create("\"", 899)
, Tuple.Create(Tuple.Create("", 875), Tuple.Create<System.Object, System.Int32>(Href("~/Template/css/style.css")
, 875), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <!-- plugins css -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 959), Tuple.Create("\"", 1036)
, Tuple.Create(Tuple.Create("", 966), Tuple.Create<System.Object, System.Int32>(Href("~/Template/css/plugins/datetimepicker/bootstrap-datetimepicker.min.css")
, 966), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1068), Tuple.Create("\"", 1129)
, Tuple.Create(Tuple.Create("", 1075), Tuple.Create<System.Object, System.Int32>(Href("~/Template/css/plugins/switch/bootstrap-switch.min.css")
, 1075), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1161), Tuple.Create("\"", 1248)
, Tuple.Create(Tuple.Create("", 1168), Tuple.Create<System.Object, System.Int32>(Href("~/Template/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css")
, 1168), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1280), Tuple.Create("\"", 1335)
, Tuple.Create(Tuple.Create("", 1287), Tuple.Create<System.Object, System.Int32>(Href("~/Template/css/plugins/sweetalert/sweetalert.css")
, 1287), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <!-- 页面内联样式 -->\r\n");

WriteLiteral("    ");

            
            #line 31 "..\..\Views\Shared\_Ace_Layout.cshtml"
Write(RenderSection("css", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <!-- Mainly scripts -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1467), Tuple.Create("\"", 1502)
, Tuple.Create(Tuple.Create("", 1473), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/jquery-2.1.1.js")
, 1473), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1526), Tuple.Create("\"", 1562)
, Tuple.Create(Tuple.Create("", 1532), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/bootstrap.min.js")
, 1532), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1586), Tuple.Create("\"", 1643)
, Tuple.Create(Tuple.Create("", 1592), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/plugins/metisMenu/jquery.metisMenu.js")
, 1592), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1667), Tuple.Create("\"", 1730)
, Tuple.Create(Tuple.Create("", 1673), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/plugins/slimscroll/jquery.slimscroll.min.js")
, 1673), false)
);

WriteLiteral("></script>\r\n\r\n    <!-- Custom and plugin javascript -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1799), Tuple.Create("\"", 1830)
, Tuple.Create(Tuple.Create("", 1805), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/inspinia.js")
, 1805), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1854), Tuple.Create("\"", 1898)
, Tuple.Create(Tuple.Create("", 1860), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/plugins/pace/pace.min.js")
, 1860), false)
);

WriteLiteral("></script>\r\n\r\n</head>\r\n<body");

WriteLiteral(" style=\"background-color:#ffffff\"");

WriteLiteral(">\r\n    <!--页面具体内容-->\r\n    <div");

WriteLiteral(" style=\"background-color:#ffffff\"");

WriteLiteral(">\r\n        <!--页头-->\r\n        <div");

WriteLiteral(" class=\"wrapper border-bottom page-heading\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 49 "..\..\Views\Shared\_Ace_Layout.cshtml"
       Write(Html.Partial("_Ace_Layout_Nav"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <!--具体页面-->\r\n        <div");

WriteLiteral(" class=\"wrapper wrapper-content\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 53 "..\..\Views\Shared\_Ace_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 55 "..\..\Views\Shared\_Ace_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Shared\_Ace_Layout.cshtml"
         if (DbRunTimeModule.Enable)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(" style=\"padding-bottom:50px;background-color:transparent;border-top:0px solid #ff" +
"ffff;\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 58 "..\..\Views\Shared\_Ace_Layout.cshtml"
           Write(Html.Raw(DbRunTimeModule.GetInfo()));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 60 "..\..\Views\Shared\_Ace_Layout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"footer\"");

WriteLiteral(">\r\n            <div>\r\n                <strong>Copyright</strong> WsLink Company &" +
"copy; 2014-");

            
            #line 63 "..\..\Views\Shared\_Ace_Layout.cshtml"
                                                                 Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <!-- plugin javascript-->\r\n" +
"    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2766), Tuple.Create("\"", 2840)
, Tuple.Create(Tuple.Create("", 2772), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/plugins/datetimepicker/bootstrap-datetimepicker.min.js")
, 2772), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2864), Tuple.Create("\"", 2948)
, Tuple.Create(Tuple.Create("", 2870), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/plugins/datetimepicker/locales/bootstrap-datetimepicker.zh-CN.js")
, 2870), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2972), Tuple.Create("\"", 3030)
, Tuple.Create(Tuple.Create("", 2978), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/plugins/switch/bootstrap-switch.min.js")
, 2978), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3054), Tuple.Create("\"", 3110)
, Tuple.Create(Tuple.Create("", 3060), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/plugins/sweetalert/sweetalert.min.js")
, 3060), false)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3136), Tuple.Create("\"", 3165)
, Tuple.Create(Tuple.Create("", 3142), Tuple.Create<System.Object, System.Int32>(Href("~/Template/cube/Cube.js")
, 3142), false)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $('select').addClass(""form-control"");
        //$(""input[type=checkbox]"").bootstrapSwitch();
        $(""input.chkSwitch"").bootstrapSwitch();

        $("".form_datetime"").datetimepicker({
            format: $(this).attr(""dateformat""),
            language: ""zh-CN"",
            autoclose: true,
            todayBtn: true,
            pickerPosition: ""bottom-left""
        });

        ");

WriteLiteral(@"
        $('tr').dblclick(function () {
            var $this = $(this);
            var row = $this.closest(""tr"");
            var findcell = row.find('.editcell');
            if (findcell.length > 0) window.location.href = findcell.attr(""href"");
        });

        var ua = navigator.userAgent.toLowerCase();
        var _parent = self.parent;
        if (/iphone|ipad|ipod/.test(ua)) {
            if (_parent) {
                $(""#wrapper"").width(self.parent.window.innerWidth);
            }
        } else if (/android/.test(ua)) {
            var w = window.screen.width;
            var k = $(document).width();
            if (k > w && k < 1000) {
                if (_parent) {
                    $(""#wrapper"").width(self.parent.window.innerWidth);
                }
            }
        }

    </script>
    <!-- 独立页面脚本 -->
");

WriteLiteral("    ");

            
            #line 116 "..\..\Views\Shared\_Ace_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
