#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Xwater_Layout.cshtml")]
    public partial class _Views_Shared__Xwater_Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Xwater_Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Shared\_Xwater_Layout.cshtml"
  
    Layout = "~/Views/Shared/_Ace_Layout.cshtml";
    ViewBag.Title = "_Xwater_Layout";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--示例,具体内容需要重写-->\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral("> ");

            
            #line 10 "..\..\Views\Shared\_Xwater_Layout.cshtml"
                              Write(Html.Partial("_Xwater_Left"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Shared\_Xwater_Layout.cshtml"
                                     Write(Html.Partial("_Xwater_Data_Profile"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                        <div></div>\r\n                    </div>\r\n             " +
"   </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-4 col-md-offset-4\"");

WriteLiteral(">");

            
            #line 19 "..\..\Views\Shared\_Xwater_Layout.cshtml"
                                             Write(Html.Partial("_Xwater_Data_Detail"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
