#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\List.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 2 "..\..\Views\Shared\List.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\List.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/List.cshtml")]
    public partial class _Views_Shared_List_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_List_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\List.cshtml"
  
    Layout = NewLife.Cube.Setting.Current.Layout;

    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;

    var enableSelect = this.EnableSelect();

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ibox float-e-margins\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"ibox-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"padding:0 15px 10px 15px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 18 "..\..\Views\Shared\List.cshtml"
               Write(Html.Partial("_List_Toolbar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 21 "..\..\Views\Shared\List.cshtml"
               Write(Html.Partial("_List_Data"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <!--分页-->\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(" style=\"background-color:transparent;border-top:0px solid #ffffff;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\Shared\List.cshtml"
               Write(Html.Partial("_List_Pager"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r" +
"\n");

DefineSection("css", () => {

WriteLiteral("\r\n\r\n");

});

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        function DeleteList(id) {
            swal({
                title: ""确定删除?"",
                //type: ""warning"",
                showCancelButton: true,
                confirmButtonColor: ""#DD6B55"",
                confirmButtonText: ""确定"",
                cancelButtonText: ""取消"",
                closeOnConfirm: false,
                closeOnCancel: true
            },
                function (isConfirm) {
                    if (isConfirm) {
                        swal({ title: ""删除成功!"", type: ""success"", timer: 1500 });
                        setTimeout(function () { location = $(""#delete_"" + id).val(); }, 1000);
                    }
                });
        }

    </script>
");

            
            #line 56 "..\..\Views\Shared\List.cshtml"
    
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Shared\List.cshtml"
     if (enableSelect)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script>\r\n            $(function () {\r\n                var $toolbarContex" +
"t = $(\'.toolbar-batch\'),\r\n                    $batchButtons = $(\'button[data-act" +
"ion=\"action\"], input[data-action=\"action\"]\'), //button, input=button, a 3种类型都可以\r" +
"\n                    $table = $(\'.table\'),\r\n                    $keys = $(\'input" +
"[name=\"keys\"]\', $table);\r\n\r\n                $table.on(\'click\', \'#chkAll\', functi" +
"on () {\r\n                    // 全选\r\n                    $keys.prop(\'checked\', th" +
"is.checked);\r\n                    // 启用禁用批量操作区\r\n                    $batchButton" +
"s.prop(\'disabled\', !this.checked);\r\n                });\r\n\r\n                $tabl" +
"e.on(\'click.checked\', \'tbody input[name=\"keys\"]\', function (e) {\r\n              " +
"      //页面中所有的checkbox\r\n                    var allbox = $table.find(\'tbody :che" +
"ckbox[name=\"keys\"]\');\r\n                    //页面中所选中的checkbox\r\n                  " +
"  var selecteds = $table.find(\'tbody :checkbox:checked[name=\"keys\"]\');\r\n        " +
"            if (selecteds.length > 0) {\r\n                        // 启用禁用批量操作区\r\n " +
"                       $batchButtons.prop(\'disabled\', false);\r\n                 " +
"       //需要判断当前页面所有行的checkbox是否都选中，以此来决定是否需要改变checkbox#chkAll 的状态\r\n             " +
"           if (allbox.length == selecteds.length) {\r\n                           " +
" $table.find(\'#chkAll\').prop(\'checked\', true);\r\n                        } else {" +
"\r\n                            $table.find(\'#chkAll\').prop(\'checked\', false);\r\n  " +
"                      }\r\n                    }\r\n                    else {\r\n    " +
"                    $batchButtons.prop(\'disabled\', true);\r\n                     " +
"   $table.find(\'#chkAll\').prop(\'checked\', false);\r\n                    }\r\n      " +
"          });\r\n            })\r\n        </script>\r\n");

            
            #line 94 "..\..\Views\Shared\List.cshtml"
    }

            
            #line default
            #line hidden
});

        }
    }
}
#pragma warning restore 1591
